# docker-compose.yml
version: '3.8'
services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: 'TestCluster'
      CASSANDRA_DC: datacenter1
