INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Die With A Smile', 'Pop', 'Lady Gaga, Bruno Mars',
  '2plbrEY59IikOBgBGLjaoe',
  'https://www.lahiguera.net/musicalia/artistas/lady_gaga/disco/14017/tema/31095/lady_gaga_die_with_a_smile-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Espresso', 'Pop', 'Sabrina Carpenter',
  '2qSkIjg1o9h3YT9RAgYN75',
  'https://www.lahiguera.net/musicalia/artistas/sabrina_carpenter/disco/13555/tema/30533/sabrina_carpenter_espresso-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Beautiful Things', 'Pop', 'Benson Boone',
  '6tNQ70jh4OwmPGpYy6R2o9',
  'https://www.lahiguera.net/musicalia/artistas/benson_boone/disco/13425/benson_boone_fireworks_&_rollerblades-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Birds of a Feather', 'chill out', 'Billie Eilish',
  '6dOtVTDdiauQNBQEDOtlAB',
  'https://www.lahiguera.net/musicalia/artistas/billie_eilish/disco/13440/billie_eilish_hit_me_hard_and_soft-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Yonaguni', 'Reggaeton', 'Bad Bunny',
  '2JPLbjOn0wPCngEot2STUS',
  'https://www.lahiguera.net/musicalia/artistas/varios/disco/0/tema/25243/yonaguni-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Lose Control', 'Pop', 'Teddy Swims',
  '6usohdchdzW9oML7VC4Uhk',
  'https://www.lahiguera.net/musicalia/artistas/teddy_swims/disco/13786/teddy_swims_ive_tried_everything_but_therapy_part_1-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Not Like Us', 'Hip-hop', 'Kendrick Lamar',
  '6AI3ezQ4o3HUoP6Dhudph3',
  'https://i.discogs.com/z8hfAi33hsNJiE11JWPSBUfIPBB9haEUEhO7MHd_0VU/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwOTgy/NDUzLTE3MTg2NTky/OTktNDc4Ni5qcGVn.jpeg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'Please Please Please', 'Pop', 'Sabrina Carpenter',
  '5N3hjp1WNayUPZrA8kJmJP',
  'https://www.lahiguera.net/musicalia/artistas/sabrina_carpenter/disco/13555/sabrina_carpenter_short_n_sweet-portada.jpg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'we can''t be friends (wait for your love)', 'Pop', 'Ariana Grande',
  '46kspZSY3aKmwQe7O77fCC',
  'https://i.discogs.com/WS9TlJh3ygxiNbA6Z8sm7CZAu1dxsyUjMNPqttx179A/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMwODI0/NzAzLTE3MTczODk5/NDYtMzg4My5qcGVn.jpeg');

INSERT INTO musica (id, title, genre, artist, source, image_url)
VALUES (uuid(), 'i like the way you kiss me', 'Pop', 'Artemas',
  '28BHwinU69xKIlL7vVln2k',
  'https://i.discogs.com/3MaCgLLj2El8PP0mmAEYFzd1W8ru9pQWfNy-S9YBGuM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTMyMTcz/NzA3LTE3MzA1MjM4/MTctODg2NS5qcGVn.jpeg');
